#!/usr/bin/env bash
#Requirement: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
#Bug: sudo nginx status returns 'not running'; netstat -lpn does not show port 80
#Solution: https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80

cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start


