#!/usr/bin/env bash
#rm /etc/nginx/sites-enabled/default
#ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo sed -i "s/sites-enabled/sites-available" /etc/nginx/nginx.conf
sudo systemctl restart nginx.service
